# Introduction
The pandas library has emerged into a power house of data manipulation tasks in python since it was developed in 2008. With its intuitive syntax and flexible data structure, it's easy to learn and enables faster data computation. The development of numpy and pandas libraries has extended python's multi-purpose nature to solve machine learning problems as well. The acceptance of python language in machine learning has been phenomenal since then.
This notebook talks about using numpy and pandas libraries for data manipulation from scratch.


## Tabel of Contents
1. Some important points about Numpy and Pandas
2. Beginning with Numpy
3. Beginning with Pandas
4. Exploring a Machine Learning Data Set
5. Building a Random Forest Model

## Some important points about Numpy and Panda
1. Data manipulation capabiltiies of Pandas is built on top of NumPy. So pandas can be stated as a dependency of numpy.
2. Pandas is best at handling tabular data sets comprising different variable types (integer, float, double, etc.). In addition, the pandas library can also be used to perform even the most naive of tasks such as loading data or doing feature engineering on time series data.
3. Numpy is most suitable and generally used for performing basic numerical and statistical computations such as mean, median, range, etc. Alongside, it also supports the creation of multi-dimensional arrays.
4. Numpy library can also be used to integrate C/C++ and Fortran code.


### Beginning with numpy

In [3]:
import numpy as np    #importing the numpy module as np
np.__version__        #checking the version of numpy

'1.11.3'

In [7]:
L=list(range(10))  #creating a list with range 0-9
print(L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [9]:
[str(c) for c in L]    #converting integers to list. this is called list comprehension.

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [10]:
[type(item) for item in L]  #finding out the data-type of each element in list

[int, int, int, int, int, int, int, int, int, int]

#### Let's create some arrays
Numpy array are homogeneous in nature. This means that the elements that they contain can only be of on data-type. All the elements have to be either int, float, double, etc

In [16]:
#creating an array with all elements as 0
np.zeros(10, dtype='int')   #10 defines the range of array and dtype declares the data type as integer

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
#creating a 4 row x 3 column matrix with all elements as 1
np.ones((4,3), dtype='int')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [22]:
#creating a matrix with predefined values 
np.full((3,5),215.4553)

array([[ 215.4553,  215.4553,  215.4553,  215.4553,  215.4553],
       [ 215.4553,  215.4553,  215.4553,  215.4553,  215.4553],
       [ 215.4553,  215.4553,  215.4553,  215.4553,  215.4553]])

In [26]:
# creatinga n array with set sequence
np.arange(0,20,2)     
#arguement explaination: array should start from 0, end at 20 and diffrence between each element should be 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
#create an array of even space between the given range of values
np.linspace(0,1,5)
#arguement explaination: array should start at 0, should end at 1 and lay 5 elements between 0 and 1 with equal distribution.

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [40]:
#creating a 3x3 array with mean=0 and standard deviation=1 in a given dimension. Normal(Gaussian) distribution in this case
np.random.normal(0,1,(3,3))

array([[ 1.27590605, -0.35045001, -0.02013599],
       [-0.072582  ,  0.47355727,  0.53815019],
       [-0.53629302, -0.37289977, -0.12854672]])

In [42]:
#creating an identity matrix
np.eye(3) #3 is to define that the matrix will be 3x3

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [47]:
#setting a random seed
np.random.seed(0)

x1 = np.random.randint(10, size=6) #one dimension
x2 = np.random.randint(10, size=(3,4)) #two dimension
x3 = np.random.randint(10, size=(3,4,5)) #three dimension

print("x1 ndim:", x2.ndim)
print("x1 shape:", x2.shape)
print("x1 size: ", x2.size)
print("x2 ndim:", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size: ", x2.size)
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x1 ndim: 2
x1 shape: (3, 4)
x1 size:  12
x2 ndim: 2
x2 shape: (3, 4)
x2 size:  12
x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size:  60


#### Array indexing
